#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Apr 19 12:36:46 +03 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 5e41c5f2cd424ac79760eafb0f34802e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot sorter_wrapper_test_behav xil_defaultlib.sorter_wrapper_test -log elaborate.log"
xelab -wto 5e41c5f2cd424ac79760eafb0f34802e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot sorter_wrapper_test_behav xil_defaultlib.sorter_wrapper_test -log elaborate.log

