#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 19 11:15:22 +03 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim sorter_wrapper_test_behav -key {Behavioral:sim_1:Functional:sorter_wrapper_test} -tclbatch sorter_wrapper_test.tcl -protoinst "protoinst_files/bd_3914.protoinst" -log simulate.log"
xsim sorter_wrapper_test_behav -key {Behavioral:sim_1:Functional:sorter_wrapper_test} -tclbatch sorter_wrapper_test.tcl -protoinst "protoinst_files/bd_3914.protoinst" -log simulate.log

